### ISSUE TITLE
The option --dest-dir=DEST_DIR is mandatory

### ISSUE THREAD

**Issue by aosthof** [SUSE-Enceladus/keg#58]
... although the help text reads different:

```
-d DEST_DIR, --dest-dir=DEST_DIR
        Destination directory for generated description, default cwd
```

Calling keg without that option will result in a stack trace:

```
$ keg -r keg-recipes sles/byos/15-sp4
[ ERROR   ]: 15:08:34 | Unexpected error:
Traceback (most recent call last):
  File "/usr/bin/keg", line 33, in <module>
    sys.exit(load_entry_point('kiwi-keg==1.1.0', 'console_scripts', 'keg')())
  File "/usr/lib/python3.8/site-packages/kiwi_keg/keg.py", line 135, in main
    image_generator = KegGenerator(
  File "/usr/lib/python3.8/site-packages/kiwi_keg/generator.py", line 44, in __init__
    if not os.path.isdir(dest_dir):
  File "/usr/lib64/python3.8/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

**Comment by jgleissner** [comment]
Default now works.
