### ISSUE TITLE
Pypi version of Keg (0.0.6) referenced in installation instructions needs updated

### ISSUE THREAD

**Issue by KeithMnemonic** [SUSE-Enceladus/keg#64]
The docs  https://documentation.suse.com/keg/1/pdf/keg_color_en.pdf mention installing via pypi. The problem is the pypi version is old 0.0.6 https://pypi.org/project/kiwi-keg/  and using that version  the list-recipes options does not work.

output from version 0.0.6

```
(azure-img-utils) kberger@keith-wks:~/repos/github> keg -l -r /home/kberger/repos/github/keg-recipes/images
[ ERROR   ]: 15:29:29 | Unexpected error:
Traceback (most recent call last):
  File "/home/kberger/venv/azure-img-utils/bin/keg", line 8, in <module>
    sys.exit(main())
  File "/home/kberger/venv/azure-img-utils/lib/python3.8/site-packages/kiwi_keg/keg.py", line 100, in main
    image_generator = KegGenerator(
  File "/home/kberger/venv/azure-img-utils/lib/python3.8/site-packages/kiwi_keg/generator.py", line 47, in __init__
    if not os.path.isdir(dest_dir):
  File "/usr/lib64/python3.8/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```
but if you install via the github repo. you get the expected output

```
(azure-img-utils) kberger@keith-wks:~/repos/github> keg -l -r /home/kberger/repos/github/keg-recipes/
Source                         Name                           Version  Description
leap/jeos/15.2                 Leap15.2-JeOS                  1.15.2   Leap 15.2 guest image
sles-sap/azure-li/15-sp2       SLES15-SP2-SAP-Azure-LI-BYOS   1.0.42   SUSE Linux Enterprise Server for SAP Applications 15 SP2 Azure LI BYOS guest image
sles-sap/azure-li/15-sp3       SLES15-SP3-SAP-Azure-LI-BYOS   0.9.1    SUSE Linux Enterprise Server for SAP Applications 15 SP3 Azure LI BYOS guest image
```

**Comment by jgleissner** [comment]
IIRC there was a typo in the code that prevented `-l` from working, only `--list-recipes`. This was fixed a while ago, but the version in pypi is really old.

**Comment by t-ru** [comment]
check out from git.

remove 0.0.6:
`sudo pip uninstall kiwi-keg

install git version
`sudo python38 steup.py install``

GIT Version is 1.1.0

@schaefi : Please update pipy.org

**Comment by jgleissner** [comment]
Version in pypi has been updated.
