### ISSUE TITLE
Improve error handling of "keg -l"

### ISSUE THREAD

**Issue by aosthof** [SUSE-Enceladus/keg#71]
I'm currently getting a traceback when trying to list the available recipes:

```
$ keg -l -r keg-recipes
Traceback (most recent call last):
  File "/usr/bin/keg", line 11, in <module>
    load_entry_point('kiwi-keg==1.2.0', 'console_scripts', 'keg')()
  File "/usr/lib/python3.6/site-packages/kiwi_keg/keg.py", line 112, in main
    image_definition.populate()
  File "/usr/lib/python3.6/site-packages/kiwi_keg/image_definition.py", line 132, in populate
    self._update_profiles(self._data.get('include-paths'))
  File "/usr/lib/python3.6/site-packages/kiwi_keg/image_definition.py", line 141, in _update_profiles
    self._expand_profile_includes(profile_data, profile, include_paths)
  File "/usr/lib/python3.6/site-packages/kiwi_keg/image_definition.py", line 184, in _expand_profile_includes
    include_paths
  File "/usr/lib/python3.6/site-packages/kiwi_keg/file_utils.py", line 85, in get_recipes
    rmerge(desc_yaml, merged_tree)
  File "/usr/lib/python3.6/site-packages/kiwi_keg/file_utils.py", line 50, in rmerge
    rmerge(value, node, ref_node)
  File "/usr/lib/python3.6/site-packages/kiwi_keg/file_utils.py", line 50, in rmerge
    rmerge(value, node, ref_node)
  File "/usr/lib/python3.6/site-packages/kiwi_keg/file_utils.py", line 58, in rmerge
    dest[key] = value
TypeError: list indices must be integers or slices, not str
```

Keg should handle errors in recipes gracefully, potentially skipping erroneous recipes and only output the valid ones.

**Comment by jgleissner** [comment]
Fix merged.
